var searchData=
[
  ['c_20code_20contributions_0',['Checklist for C++ code contributions',['../md_CONTRIBUTING.html#autotoc_md24',1,'']]],
  ['callback_1',['ctbench_add_custom_benchmark(name source begin end step samples callback)',['../md_generated-docs_2ctbench-api.html#autotoc_md38',1,'']]],
  ['case_20target_2',['Declaring a benchmark case target',['../index.html#autotoc_md55',1,'']]],
  ['category_20config_20benchmarks_3',['ctbench_add_graph(category config benchmarks...)',['../md_generated-docs_2ctbench-api.html#autotoc_md40',1,'']]],
  ['cd_4',['CI/CD',['../md_CHANGELOG.html#autotoc_md4',1,'']]],
  ['changelog_5',['Changelog',['../md_CHANGELOG.html',1,'']]],
  ['changelog_2emd_6',['CHANGELOG.md',['../CHANGELOG_8md.html',1,'']]],
  ['changes_7',['Make Changes',['../md_CONTRIBUTING.html#autotoc_md23',1,'']]],
  ['check_8',['check',['../namespacegrapher.html#a4dc38155d6bf6e2c7c447a07a03f4e79',1,'grapher']]],
  ['checklist_20for_20c_20code_20contributions_9',['Checklist for C++ code contributions',['../md_CONTRIBUTING.html#autotoc_md24',1,'']]],
  ['checklist_20for_20cmake_20api_20code_20contributions_10',['Checklist for CMake API code contributions',['../md_CONTRIBUTING.html#autotoc_md25',1,'']]],
  ['ci_20cd_11',['CI/CD',['../md_CHANGELOG.html#autotoc_md4',1,'']]],
  ['citing_20ctbench_12',['Citing ctbench',['../index.html#autotoc_md59',1,'']]],
  ['cli_13',['cli',['../namespacecli.html',1,'']]],
  ['cli_2ecpp_14',['cli.cpp',['../cli_8cpp.html',1,'']]],
  ['cli_2ehpp_15',['cli.hpp',['../cli_8hpp.html',1,'']]],
  ['cmake_20api_20code_20contributions_16',['Checklist for CMake API code contributions',['../md_CONTRIBUTING.html#autotoc_md25',1,'']]],
  ['cmake_20api_20documentation_20explainer_17',['CMake API documentation explainer',['../md_CONTRIBUTING.html#autotoc_md26',1,'']]],
  ['cmake_20api_20reference_18',['CMake API reference',['../md_generated-docs_2ctbench-api.html',1,'']]],
  ['cmake_2ddoc_2dextractor_2ecpp_19',['cmake-doc-extractor.cpp',['../cmake-doc-extractor_8cpp.html',1,'']]],
  ['code_20contributions_20',['code contributions',['../md_CONTRIBUTING.html#autotoc_md24',1,'Checklist for C++ code contributions'],['../md_CONTRIBUTING.html#autotoc_md25',1,'Checklist for CMake API code contributions']]],
  ['code_20of_20conduct_21',['Contributor Covenant Code of Conduct',['../md_CODE__OF__CONDUCT.html',1,'']]],
  ['code_5fof_5fconduct_2emd_22',['CODE_OF_CONDUCT.md',['../CODE__OF__CONDUCT_8md.html',1,'']]],
  ['command_5fenum_5ft_23',['command_enum_t',['../namespacecli.html#a67216dd61bcb01d32a580b662469cabd',1,'cli']]],
  ['command_5fopt_24',['command_opt',['../namespacecli.html#aa700471cf364ea8abaa378d0fbc1c56b',1,'cli']]],
  ['compare_25',['compare',['../plotter_config.html#autotoc_md46',1,'']]],
  ['compare_2ecpp_26',['compare.cpp',['../compare_8cpp.html',1,'']]],
  ['compare_2ehpp_27',['compare.hpp',['../compare_8hpp.html',1,'']]],
  ['compare_5fby_28',['compare_by',['../plotter_config.html#autotoc_md47',1,'']]],
  ['compare_5fby_2ecpp_29',['compare_by.cpp',['../compare__by_8cpp.html',1,'']]],
  ['compare_5fby_2ehpp_30',['compare_by.hpp',['../compare__by_8hpp.html',1,'']]],
  ['compare_5fby_5fv_31',['compare_by_v',['../namespacegrapher.html#aa192088d1895a94ae9eafc5cf26172a0a53d0ae41552a57745d578f34ba6062ae',1,'grapher']]],
  ['compare_5fv_32',['compare_v',['../namespacegrapher.html#aa192088d1895a94ae9eafc5cf26172a0aa167fef5ad47df71c356ee21bdb03204',1,'grapher']]],
  ['compiler_33',['ctbench_set_compiler(compiler)',['../md_generated-docs_2ctbench-api.html#autotoc_md42',1,'']]],
  ['compiler_20launcher_34',['compiler-launcher',['../md_CHANGELOG.html#autotoc_md2',1,'']]],
  ['compiler_2dlauncher_2ecpp_35',['compiler-launcher.cpp',['../compiler-launcher_8cpp.html',1,'']]],
  ['conduct_36',['Contributor Covenant Code of Conduct',['../md_CODE__OF__CONDUCT.html',1,'']]],
  ['config_20benchmarks_37',['ctbench_add_graph(category config benchmarks...)',['../md_generated-docs_2ctbench-api.html#autotoc_md40',1,'']]],
  ['config_5fopt_38',['config_opt',['../namespacecli.html#ad8e6b38f38dd5d1d063df10309e81a12',1,'cli']]],
  ['configuration_20documentation_39',['Plotter configuration documentation',['../plotter_config.html',1,'']]],
  ['contributing_20guide_40',['Welcome to ctbench contributing guide',['../md_CONTRIBUTING.html',1,'']]],
  ['contributing_2emd_41',['CONTRIBUTING.md',['../CONTRIBUTING_8md.html',1,'']]],
  ['contributions_42',['contributions',['../md_CONTRIBUTING.html#autotoc_md24',1,'Checklist for C++ code contributions'],['../md_CONTRIBUTING.html#autotoc_md25',1,'Checklist for CMake API code contributions']]],
  ['contributor_20covenant_20code_20of_20conduct_43',['Contributor Covenant Code of Conduct',['../md_CODE__OF__CONDUCT.html',1,'']]],
  ['contributor_20guide_44',['New contributor guide',['../md_CONTRIBUTING.html#autotoc_md18',1,'']]],
  ['core_2ehpp_45',['core.hpp',['../core_8hpp.html',1,'']]],
  ['correction_46',['1. Correction',['../md_CODE__OF__CONDUCT.html#autotoc_md12',1,'']]],
  ['covenant_20code_20of_20conduct_47',['Contributor Covenant Code of Conduct',['../md_CODE__OF__CONDUCT.html',1,'']]],
  ['create_20a_20new_20issue_48',['Create a new issue',['../md_CONTRIBUTING.html#autotoc_md21',1,'']]],
  ['ctbench_49',['ctbench',['../index.html#autotoc_md59',1,'Citing ctbench'],['../index.html',1,'ctbench'],['../index.html#autotoc_md53',1,'Installing ctbench'],['../index.html#autotoc_md51',1,'Using ctbench']]],
  ['ctbench_20contributing_20guide_50',['Welcome to ctbench contributing guide',['../md_CONTRIBUTING.html',1,'']]],
  ['ctbench_20graph_20all_20target_51',['ctbench-graph-all target',['../md_generated-docs_2ctbench-api.html#autotoc_md30',1,'']]],
  ['ctbench_20in_20your_20project_52',['Integrating ctbench in your project',['../index.html#autotoc_md54',1,'']]],
  ['ctbench_2dapi_2emd_53',['ctbench-api.md',['../ctbench-api_8md.html',1,'']]],
  ['ctbench_5fadd_5fbenchmark_20name_20source_20begin_20end_20step_20samples_54',['ctbench_add_benchmark(name source begin end step samples)',['../md_generated-docs_2ctbench-api.html#autotoc_md32',1,'']]],
  ['ctbench_5fadd_5fbenchmark_5ffor_5frange_20name_20source_20range_5fparams_20samples_55',['ctbench_add_benchmark_for_range(name source range_params samples)',['../md_generated-docs_2ctbench-api.html#autotoc_md34',1,'']]],
  ['ctbench_5fadd_5fbenchmark_5ffor_5fsize_5flist_20name_20source_20begin_20end_20step_20samples_56',['ctbench_add_benchmark_for_size_list(name source begin end step samples)',['../md_generated-docs_2ctbench-api.html#autotoc_md36',1,'']]],
  ['ctbench_5fadd_5fcustom_5fbenchmark_20name_20source_20begin_20end_20step_20samples_20callback_57',['ctbench_add_custom_benchmark(name source begin end step samples callback)',['../md_generated-docs_2ctbench-api.html#autotoc_md38',1,'']]],
  ['ctbench_5fadd_5fgraph_20category_20config_20benchmarks_58',['ctbench_add_graph(category config benchmarks...)',['../md_generated-docs_2ctbench-api.html#autotoc_md40',1,'']]],
  ['ctbench_5fset_5fcompiler_20compiler_59',['ctbench_set_compiler(compiler)',['../md_generated-docs_2ctbench-api.html#autotoc_md42',1,'']]],
  ['ctbench_5funset_5fcompiler_60',['ctbench_unset_compiler()',['../md_generated-docs_2ctbench-api.html#autotoc_md44',1,'']]],
  ['curve_5faggregate_5fmap_5ft_61',['curve_aggregate_map_t',['../namespacegrapher_1_1plotters.html#aef6f395c6dc72130f02da5edf5b6574b',1,'grapher::plotters']]],
  ['curve_5faggregate_5ft_62',['curve_aggregate_t',['../namespacegrapher_1_1plotters.html#a9bbe1c9b4d638629ad74f1b268eaac63',1,'grapher::plotters']]]
];
